name: Tests

on: [pull_request]

jobs:
  matlab-tests:
    runs-on: self-hosted

    steps:
      - name: Fetch RAVEN
        uses: actions/checkout@v3
        with:
          repository: "SysBioChalmers/RAVEN"
          path: "RAVEN"

      - name: Fetch GECKO
        uses: actions/checkout@v3

      - name: Run tests
        id: matlab-test
        run: |
          TEST_RESULTS=$(/usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "addpath(genpath('RAVEN')); checkInstallation; GECKOInstaller.install; runtests('geckoCoreFunctionTests')")
          PARSED_RESULTS=$(echo $TEST_RESULTS | awk -F'com\\.' '{ n = split($2, v, "(___+)|(===+)|(---+)"); for (i = 0; ++i <= n;) { print v[i] } }')
          PARSED_RESULTS="${PARSED_RESULTS//'%'/'%25'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\n'/'<br>'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\r'/'<br>'}"
          echo "results=$PARSED_RESULTS" >> $GITHUB_OUTPUT

      - name: Post comment
        uses: NejcZdovc/comment-pr@v2
        with:
          file: "commentsFromTests.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TEST_RESULTS: ${{steps.matlab-test.outputs.results}}
          GH_ACTION_RUN: ${{github.run_id}}
